[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "apscheduler>=3.11.3",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.124.4",
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
    "pywebview[qt]>=6.2.1",
    "requests>=2.32.4",
    "rich>=14.3.4",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.51",
]
