name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build
        run: |
          uv run pyinstaller \
            --windowed \
            --name Appointments \
            --add-data "app:app" \
            --add-data "database:database" \
            --add-data "static:static" \
            --add-data "main.py:." \
            --add-data ".env:." \
            UI.py


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Appointments-Windows
          path: dist/**